platform :ios, "11.0"
inhibit_all_warnings!
def main_pods
pod 'AFNetworking', '2.6.3'
    pod 'AFNetworkActivityLogger'
    pod 'Reachability', '3.2'
    pod 'MagicalRecord', '2.3.2', :inhibit_warnings => true
    pod 'ReactiveObjC'
end
